/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unibo.it;

public class Dashboard {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Dashboard().getGreeting());
    }
}
